import { ModalProvider } from '@components/customized-modal';
import Header from '@layout/header';
import Menu from '@layout/menu';

import './globals.css';

export const metadata = {
    title: 'My Voca',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <body>
                <ModalProvider>
                    <div className="min-h-screen w-full bg-gray-100">
                        <Header />
                        <Menu />
                        <main className="mx-auto min-h-screen w-full max-w-md border-x border-slate-300 bg-slate-50 px-5 pt-20 dark:bg-slate-900 max-sm:max-w-full max-sm:border-x-0 max-sm:px-2.5 max-sm:pt-16">
                            {children}
                        </main>
                    </div>
                </ModalProvider>
            </body>
        </html>
    );
}
