import { ModalProvider } from '@components/customized-modal';
import Header from '@layout/header';
import Menu from '@layout/menu';

import './globals.css';

export const metadata = {
    title: 'My Voca',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <body>
                <ModalProvider>
                    <div className="min-h-screen w-full bg-slate-50 dark:bg-slate-900">
                        <Header />
                        <Menu />
                        <main className="min-h-screen w-full p-5 pt-[80px]">{children}</main>
                    </div>
                </ModalProvider>
            </body>
        </html>
    );
}
